# See https://cloud.google.com/appengine/docs/flexible/nodejs/configuring-your-app-with-app-yaml
runtime: nodejs
env: flex
network:
  instance_tag: base
  name: default
health_check:
  enable_health_check: True
  check_interval_sec: 5
  timeout_sec: 5
  unhealthy_threshold: 4
  healthy_threshold: 2
  restart_threshold: 12
resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10
# Use manual scaling with a static number of instances
# See documentation here: https://cloud.google.com/appengine/docs/flexible/nodejs/configuring-your-app-with-app-yaml#manual-scaling
manual_scaling:
  instances: 1
# Use automatic_scaling to scale based on Target CPU utilization
# See documentation here: https://cloud.google.com/appengine/docs/flexible/nodejs/configuring-your-app-with-app-yaml#auto-scaling
#automatic_scaling:
#  min_num_instances: 1
#  max_num_instances: 1 # 20 = default value
#  cool_down_period_sec: 60 # 120 = default value -- The time interval between auto scaling checks.
#  cpu_utilization:
#    target_utilization: 0.5  # 0.5 = default value -- Target CPU utilization (default 0.5). CPU use is averaged across all running instances and is used to decide when to reduce or increase the number of instances.
skip_files:
  - ^node_modules/(.*/)?
  - ^\.git/.*
  - ^\.github/.*
env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: base.json
  MYSQL_USER: base
  MYSQL_PASSWORD: base
  MYSQL_DATABASE: base
  INSTANCE_CONNECTION_NAME: base:us-east1:base
  MANDRILL_KEY: base
  GOOGLE_PROJECT_ID: base
  GOOGLE_PROJECT_LOCATION: us-east1
beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: base:us-east1:base
